---
- name: Install PiHole on Docker with optional metrics and portainer agent
  
  hosts: all
  
  gather_facts: yes

  vars_files:
    - ./vars.default.yml
    - ./vars.yml

  pre_tasks:
    - name: Setup System
      become: yes
      ansible.builtin.import_tasks: ./tasks/setup-system.yml

  roles:
    - name: geerlingguy.docker
      become: yes
      vars:
        docker_install_compose: false
        docker_users: "{{ ansible_facts.user_id }}"
    - name: geerlingguy.pip
      become: yes
      vars:
        pip_install_packages:
            - name: docker
            - name: docker-compose

  tasks:
    - name: Reset connection to reload user changes
      ansible.builtin.meta: reset_connection

    - name: Setup project
      ansible.builtin.import_tasks: ./tasks/project-setup.yml

    - name: Configure pihole
      ansible.builtin.import_tasks: ./tasks/configure-pihole.yml

    - name: Install gravity-sync
      ansible.builtin.import_tasks: ./tasks/configure-gravity-sync.yml
      when: gravity_sync_install
      
    - name: Register Portainer Agent
      ansible.builtin.import_tasks: ./tasks/register-pagent.yml
      when: pagent_install and pagent_autoregister