- name: Create project folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0755'
  with_items:
    - "{{ project_dir }}"
    - "{{ config_dir }}"
    - "{{ pihole_dir }}"

- name: Template pihole compose file
  ansible.builtin.template:
    src: ./templates/docker-compose.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0644'

- name: Start docker-compose services
  community.docker.docker_compose:
    project_name: pihole
    project_src: "{{ project_dir }}"
    pull: yes