- name: Authenticate with {{ pagent_server_user }} on {{ pagent_server_host }}:{{ pagent_server_port }}
  ansible.builtin.uri:
    url: "http://{{ pagent_server_host }}:{{ pagent_server_port }}/api/auth"
    method: POST
    body_format: json
    body: 
      username: "{{ pagent_server_user }}"
      password: "{{ pagent_server_pass }}"
    status_code: 200
  register: portainer_login

- name: Register Portainer Agent
  ansible.builtin.uri:
    url: "http://{{ pagent_server_host }}:{{ pagent_server_port }}/api/endpoints"
    method: POST
    body_format: form-urlencoded
    body: 
      Name: "{{ ansible_facts.hostname }}"
      EndpointCreationType: "2"
      URL: "tcp://{{ ansible_host }}:9001"
      TLS: "true"
      TLSSkipVerify: "true"
      TLSSkipClientVerify: "true"
    headers:
      Authorization: Bearer {{ portainer_login.json.jwt }}

