- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  register: _result
  until: not _result.failed
  delay: 10
  retries: 10

- name: Update system
  ansible.builtin.apt:
    upgrade: dist
  register: _result
  until: not _result.failed
  delay: 10
  retries: 10

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - rsync
    - sqlite3
  register: _result
  until: not _result.failed
  delay: 10
  retries: 10

- name: Update timezone to {{ timezone }}
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Disable SystemD stub resolver
  ansible.builtin.import_tasks: ./tasks/deactivate-systemd-stub-resolver.yml

- name: Reboot host
  ansible.builtin.reboot:
