- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  register: _result
  until: not _result.failed
  delay: 10
  retries: 10

- name: Update system
  ansible.builtin.apt:
    upgrade: dist
  register: _result
  until: not _result.failed
  delay: 10
  retries: 10