version: "3"

services:
  portainer-agent:
    container_name: portainer-agent
    hostname: portainer-agent
    image: portainer/agent:latest
    ports:
      - "9001:9001/tcp"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
